name: Issue Workflow
on:
  issues:
    types: [opened]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Greet user
        run: |
          curl \
            -X POST \
            -H "Authorization: token ${{ secrets.MY_TOKEN }}" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/comments \
            -d '{"body":"Hello user!!
            Thanks for reporting the issue We will try to sort it out soon
            Have a nice day.\\n\\n![Image](https://i.pinimg.com/originals/95/d3/e9/95d3e90e780ad7bc70e4dd985d70493f.jpg)"}'
